import type { Config } from "tailwindcss";

// Design tokens ported 1:1 from the Stitch-exported screens
// (stitch_frontend/*/code.html inline tailwind.config) so every
// page shares one source of truth instead of re-declaring colors.
const config: Config = {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#474747",
        "surface-container-highest": "#e2e2e2",
        "surface-container": "#eeeeee",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#ddc734",
        "on-surface": "#1a1c1c",
        background: "#f9f9f9",
        "surface-container-lowest": "#ffffff",
        outline: "#7e7576",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#c6c6c6",
        "on-secondary-fixed": "#201c00",
        "tertiary-fixed": "#fcd7ff",
        "error-container": "#ffdad6",
        "inverse-primary": "#c6c6c6",
        "surface-dim": "#dadada",
        "surface-container-high": "#e8e8e8",
        "surface-container-low": "#f3f3f4",
        error: "#ba1a1a",
        "surface-variant": "#e2e2e2",
        secondary: "#6b5f00",
        "on-primary-container": "#848484",
        "on-secondary-fixed-variant": "#504700",
        "on-tertiary-fixed": "#340043",
        "outline-variant": "#cfc4c5",
        "on-tertiary-fixed-variant": "#73198c",
        surface: "#f9f9f9",
        "on-primary": "#ffffff",
        "tertiary-container": "#340043",
        "primary-container": "#1b1b1b",
        primary: "#000000",
        "surface-bright": "#f9f9f9",
        "inverse-surface": "#2f3131",
        "on-secondary-container": "#726500",
        "surface-tint": "#5e5e5e",
        "inverse-on-surface": "#f0f1f1",
        "on-background": "#1a1c1c",
        "tertiary-fixed-dim": "#f2afff",
        "on-error": "#ffffff",
        "primary-fixed": "#e2e2e2",
        "on-surface-variant": "#4c4546",
        "secondary-fixed": "#fbe44f",
        "on-primary-fixed": "#1b1b1b",
        tertiary: "#000000",
        "secondary-container": "#fbe44f",
        "on-tertiary-container": "#b85fd0",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        gutter: "1rem",
        "margin-tablet": "1.5rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-md": "1rem",
        "gutter-sm": "0.5rem",
        margin: "1rem",
        "space-sm": "0.5rem",
        "space-xs": "0.25rem",
        "margin-desktop": "2.5rem",
      },
      fontFamily: {
        "headline-md": ["Space Grotesk"],
        "headline-lg": ["Space Grotesk"],
        "label-lg": ["Space Grotesk"],
        "label-sm": ["Space Grotesk"],
        "display-lg": ["Space Grotesk"],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Space Grotesk"],
        "display-lg-mobile": ["Space Grotesk"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "700" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "700" }],
        "display-lg": ["36px", { lineHeight: "40px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "700" }],
        "display-lg-mobile": ["26px", { lineHeight: "30px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
